### ISSUE TITLE
xcode 15 compile issue. (SDK has old swift version)

### ISSUE THREAD

**Issue by Shahbaz-Akram** [complycube/complycube-ios-sample#1]
Failed to build module 'ComplyCubeMobileSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.

<img width="661" alt="Screenshot 2023-10-19 at 7 30 57 AM" src="https://github.com/complycube/complycube-ios-sdk/assets/8728903/9efc783b-21b5-4516-b3d4-6d28f9c876be">

**Comment by hamza7171** [comment]
Same issue for me

**Comment by hkvcc** [comment]
Please ensure you use the latest version from cc-cocoapods-release-local and not a release candidate or nightly build. This is not present in the latest release version.
